### ISSUE TITLE
Demo broken on Safari

### ISSUE THREAD

**Issue by zachleat** [tuateam/tua-body-scroll-lock#27]
**Describe the bug**
Scrolling doesn’t work on the CodePen demo: https://codepen.io/buptsteve/full/EJoKQK

![image](https://user-images.githubusercontent.com/39355/62965532-e8e6e400-bdca-11e9-9286-bb8a3a335414.png)

**To Reproduce**
1. Go to https://codepen.io/buptsteve/full/EJoKQK
2. Click the 'click me to show the dialog' button
3. Click outside the dialog to close the dialog
4. Page no longer is scrollable

**Comment by evinma** [comment]
![image](https://user-images.githubusercontent.com/16096567/62987354-f0ad9380-be71-11e9-8894-7b03aac39c8f.png)
You are using **body-scroll-lock**, but our package here is **tua-body-scroll-lock**.
Please try using **tua-body-scroll-lock** to solve your problem.

**Comment by BuptStEve** [comment]
![image](https://user-images.githubusercontent.com/11501493/62991624-d16b3200-be82-11e9-9b88-570f098131a6.png)
