### ISSUE TITLE
可以支持一下uni-app吗

### ISSUE THREAD

**Issue by jiadaoyun** [tuateam/tua-body-scroll-lock#37]
既然pc、移动端和客户端都支持了，那么请大神也支持一下小程序（微信，支付宝）这些吧，感激不尽

**Comment by BuptStEve** [comment]
小程序目前支持不了...
先在不可滚动的地方用 `catch:touchmove="noop"` 暂时顶一下吧...（`noop` 就是个空函数）

**Comment by BuptStEve** [comment]
话说现在小程序原生有解决方案了么？
