### ISSUE TITLE
feat: hope can fit  ios 11

### ISSUE THREAD

**Issue by Mowmowj** [tuateam/tua-body-scroll-lock#43]
i founded it cannot fit ios 11.2  on the iPhone 7 Plus.
actually in current market many people still use the ios 11 ,
hope this best  repositories can fit this system.

**Comment by BuptStEve** [comment]
Thank you for your issue.
I have tried it on iOS 11.0.2 iPhone 7, it's working... https://tuateam.github.io/tua-body-scroll-lock/

**Comment by Mowmowj** [comment]
thank u so much maybe it's the wechat bugs

**Comment by evinma** [comment]
no recurrence！
