### ISSUE TITLE
feat: Inhibit body content shift when toggling scroll lock

### ISSUE THREAD

**Issue by TheMangoTrain** [tuateam/tua-body-scroll-lock#44]
**Is your feature request related to a problem? Please describe.**
When enabling scroll lock, the body's scroll bar disappears, resulting in a horizontal shift of the body content (around 15-17px depending on the browser).

**Describe the solution you'd like**
For scrolling to be disabled and the body content to NOT shift.
Potential options:
A - Maintain a scroll bar even with scrolling disabled
--- or ---
B - Add padding to the body content, that matches the width of the scroll bar

**Describe alternatives you've considered**
Looked at other plugins and manual solutions online.

**Comment by evinma** [comment]
The positioning of the header element in the demo is fixed, which is out of the document flow and has been modified to sticky
