### ISSUE TITLE
bug: Demo link is old, broken on Android

### ISSUE THREAD

**Issue by TheMangoTrain** [tuateam/tua-body-scroll-lock#45]
Need to clean up the demo links....

On the Github page ([https://github.com/tuateam/tua-body-scroll-lock](https://github.com/tuateam/tua-body-scroll-lock)), there's a link "[Can't believe it? Please try this demo with BSL yourself.](https://codepen.io/buptsteve/pen/EJoKQK)" and itdoesn't seem to work (Chrome 86 on Android, Firefox 81.0.2 on MacOS).

Meanwhile, another demo link further down the page, [demo.vue](https://codepen.io/evinma/pen/OJNJdoy), **does work** across the above stated browsers.

**Comment by BuptStEve** [comment]
### **not working** ✖
[body-scroll-lock - https://github.com/willmcpo/body-scroll-lock](https://github.com/willmcpo/body-scroll-lock)
![image](https://user-images.githubusercontent.com/11501493/98057993-9df93680-1e7e-11eb-9fed-32fef17cef58.png)

### **working** ✔
tua-body-scroll-lock
![image](https://user-images.githubusercontent.com/11501493/98058168-021bfa80-1e7f-11eb-8f94-f07f2b3126a4.png)
