### ISSUE TITLE
feat: Better documentation

### ISSUE THREAD

**Issue by JamesTheBald** [tuateam/tua-body-scroll-lock#56]
**Is your feature request related to a problem? Please describe.**
It can be difficult for less experienced developers to know how to use this package.

**Describe the solution you'd like**
A clearer explanation of how to use the lock and unlock functions. The current usage explanation is just:
    import { lock, unlock } from 'tua-body-scroll-lock'
    lock()
    unlock()
The import line is clear enough. But how do you use lock() and unlock()? Where do you put them? Do these functions take parameters? An example on CodePen or similar would be great.

**Describe alternatives you've considered**
I'm going to try the useLockBodyScroll package instead. At least I can find an example of how to use it.

**Additional context**
Thanks everyone on this team for your great work!

**Comment by BuptStEve** [comment]
How about this?
https://github.com/tuateam/tua-body-scroll-lock#demo

**Comment by evinma** [comment]
No need to fix.
